[package]
name = "rust_wasm_utils"
version = "0.1.0"
authors = ["Ramil Zaynetdinov <ramil.zv@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.7"
fast_image_resize = "3.0.1"
image = "0.24.8"
rust-crypto-wasm = "0.3.1"
wasm-bindgen = "0.2.90"
